### PR TITLE
added previous episode to idata-filter

### PR DESCRIPTION
**Pull request by DxSnow**
1. added previous episode to idata-filter
2. switched to original image URL for dummy data to try out image quality

### CODE REVIEW

**Review by Guneet13 — COMMENTED** [review]
previousEpisode must be in camelCase for easy readability. Also, where schedule is declared, we need to make the array of string kind. eg: days: string[]. Otherwise, it thinks array has only one value of string kind.

**Comment by Guneet13** [comment]
Since, these were not big changes and I needed to test it, so I made the changes in the Idata-Filter file

**Comment by DxSnow** [comment]
I doubt your change to "previousEpisode" will work. I did not use camelCase because "previousepisode" is exactly how TVmaze Api wrote it. I agree that camelCase is more readable, but it does not match how TVmaze API wrote it. Since this API is a Tvmaze data filter, we should match precisely how TVmaze defines it. Would you mind checking the original data before making changes? Here is the link for your convenience: (https://api.tvmaze.com/singlesearch/shows?q=girls)

**Comment by DxSnow** [comment]
The change to string[ ] looks great. Thank you.

**Pull request merged**
